/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TimeTrackingRouteImport } from './routes/time-tracking'
import { Route as TaxRouteImport } from './routes/tax'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServiceCatalogRouteImport } from './routes/service-catalog'
import { Route as PropertyManagementRouteImport } from './routes/property-management'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PartnerNetworkRouteImport } from './routes/partner-network'
import { Route as ParalegalRouteImport } from './routes/paralegal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LocalContentRouteImport } from './routes/local-content'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as ImmigrationRouteImport } from './routes/immigration'
import { Route as ExpeditingRouteImport } from './routes/expediting'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as TimeTrackingIndexRouteImport } from './routes/time-tracking/index'
import { Route as TaxIndexRouteImport } from './routes/tax/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PayrollIndexRouteImport } from './routes/payroll/index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents/index'
import { Route as ComplianceIndexRouteImport } from './routes/compliance/index'
import { Route as ClientsIndexRouteImport } from './routes/clients/index'
import { Route as AutomationIndexRouteImport } from './routes/automation/index'
import { Route as AppointmentsIndexRouteImport } from './routes/appointments/index'
import { Route as UsersRolesRouteImport } from './routes/users/roles'
import { Route as UsersInviteRouteImport } from './routes/users/invite'
import { Route as TimeTrackingTimerRouteImport } from './routes/time-tracking.timer'
import { Route as TimeTrackingReportsRouteImport } from './routes/time-tracking.reports'
import { Route as TimeTrackingProjectsRouteImport } from './routes/time-tracking.projects'
import { Route as TimeTrackingEntriesRouteImport } from './routes/time-tracking.entries'
import { Route as TaxVatRouteImport } from './routes/tax/vat'
import { Route as TaxPayeRouteImport } from './routes/tax/paye'
import { Route as TaxNisRouteImport } from './routes/tax/nis'
import { Route as TaxFilingRouteImport } from './routes/tax/filing'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsNotificationsRouteImport } from './routes/settings/notifications'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsBackupRouteImport } from './routes/settings/backup'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as PortalPaymentsRouteImport } from './routes/portal/payments'
import { Route as PortalFilingsRouteImport } from './routes/portal/filings'
import { Route as PortalDocumentsRouteImport } from './routes/portal/documents'
import { Route as PortalAppointmentsRouteImport } from './routes/portal/appointments'
import { Route as PayrollRunRouteImport } from './routes/payroll/run'
import { Route as PayrollReportsRouteImport } from './routes/payroll/reports'
import { Route as PayrollEmployeesRouteImport } from './routes/payroll/employees'
import { Route as InvoicesPaymentsRouteImport } from './routes/invoices/payments'
import { Route as InvoicesNewRouteImport } from './routes/invoices/new'
import { Route as InvoicesIdRouteImport } from './routes/invoices/$id'
import { Route as DocumentsUploadRouteImport } from './routes/documents/upload'
import { Route as DocumentsTemplatesRouteImport } from './routes/documents/templates'
import { Route as DocumentsSearchRouteImport } from './routes/documents/search'
import { Route as DocumentsRequirementsRouteImport } from './routes/documents/requirements'
import { Route as DocumentsAdvancedRouteImport } from './routes/documents/advanced'
import { Route as DocumentsIdRouteImport } from './routes/documents/$id'
import { Route as ComplianceReportsRouteImport } from './routes/compliance/reports'
import { Route as ComplianceGraFilingRouteImport } from './routes/compliance/gra-filing'
import { Route as ComplianceAlertsRouteImport } from './routes/compliance/alerts'
import { Route as ClientsNewRouteImport } from './routes/clients/new'
import { Route as ClientsActiveRouteImport } from './routes/clients/active'
import { Route as ClientsIdRouteImport } from './routes/clients/$id'
import { Route as AutomationTemplatesRouteImport } from './routes/automation.templates'
import { Route as AutomationRulesRouteImport } from './routes/automation.rules'
import { Route as AutomationHistoryRouteImport } from './routes/automation.history'
import { Route as AppointmentsRequestsRouteImport } from './routes/appointments/requests'
import { Route as AppointmentsNewRouteImport } from './routes/appointments/new'
import { Route as AppointmentsCalendarRouteImport } from './routes/appointments/calendar'
import { Route as AppointmentsIdRouteImport } from './routes/appointments/$id'
import { Route as ClientsIdEditRouteImport } from './routes/clients/$id/edit'
import { Route as ClientsIdDocumentsRouteImport } from './routes/clients/$id/documents'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeTrackingRoute = TimeTrackingRouteImport.update({
  id: '/time-tracking',
  path: '/time-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TaxRoute = TaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceCatalogRoute = ServiceCatalogRouteImport.update({
  id: '/service-catalog',
  path: '/service-catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyManagementRoute = PropertyManagementRouteImport.update({
  id: '/property-management',
  path: '/property-management',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerNetworkRoute = PartnerNetworkRouteImport.update({
  id: '/partner-network',
  path: '/partner-network',
  getParentRoute: () => rootRouteImport,
} as any)
const ParalegalRoute = ParalegalRouteImport.update({
  id: '/paralegal',
  path: '/paralegal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalContentRoute = LocalContentRouteImport.update({
  id: '/local-content',
  path: '/local-content',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmigrationRoute = ImmigrationRouteImport.update({
  id: '/immigration',
  path: '/immigration',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpeditingRoute = ExpeditingRouteImport.update({
  id: '/expediting',
  path: '/expediting',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UsersRoute,
} as any)
const TimeTrackingIndexRoute = TimeTrackingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimeTrackingRoute,
} as any)
const TaxIndexRoute = TaxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TaxRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayrollRoute,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InvoicesRoute,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const ComplianceIndexRoute = ComplianceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComplianceRoute,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIndexRoute = AutomationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AutomationRoute,
} as any)
const AppointmentsIndexRoute = AppointmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppointmentsRoute,
} as any)
const UsersRolesRoute = UsersRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => UsersRoute,
} as any)
const UsersInviteRoute = UsersInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => UsersRoute,
} as any)
const TimeTrackingTimerRoute = TimeTrackingTimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => TimeTrackingRoute,
} as any)
const TimeTrackingReportsRoute = TimeTrackingReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => TimeTrackingRoute,
} as any)
const TimeTrackingProjectsRoute = TimeTrackingProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => TimeTrackingRoute,
} as any)
const TimeTrackingEntriesRoute = TimeTrackingEntriesRouteImport.update({
  id: '/entries',
  path: '/entries',
  getParentRoute: () => TimeTrackingRoute,
} as any)
const TaxVatRoute = TaxVatRouteImport.update({
  id: '/vat',
  path: '/vat',
  getParentRoute: () => TaxRoute,
} as any)
const TaxPayeRoute = TaxPayeRouteImport.update({
  id: '/paye',
  path: '/paye',
  getParentRoute: () => TaxRoute,
} as any)
const TaxNisRoute = TaxNisRouteImport.update({
  id: '/nis',
  path: '/nis',
  getParentRoute: () => TaxRoute,
} as any)
const TaxFilingRoute = TaxFilingRouteImport.update({
  id: '/filing',
  path: '/filing',
  getParentRoute: () => TaxRoute,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsBackupRoute = SettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPaymentsRoute = PortalPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFilingsRoute = PortalFilingsRouteImport.update({
  id: '/filings',
  path: '/filings',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAppointmentsRoute = PortalAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PortalRoute,
} as any)
const PayrollRunRoute = PayrollRunRouteImport.update({
  id: '/run',
  path: '/run',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollReportsRoute = PayrollReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollEmployeesRoute = PayrollEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => PayrollRoute,
} as any)
const InvoicesPaymentsRoute = InvoicesPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)
const DocumentsUploadRoute = DocumentsUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsTemplatesRoute = DocumentsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsSearchRoute = DocumentsSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsRequirementsRoute = DocumentsRequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsAdvancedRoute = DocumentsAdvancedRouteImport.update({
  id: '/advanced',
  path: '/advanced',
  getParentRoute: () => DocumentsRoute,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DocumentsRoute,
} as any)
const ComplianceReportsRoute = ComplianceReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ComplianceRoute,
} as any)
const ComplianceGraFilingRoute = ComplianceGraFilingRouteImport.update({
  id: '/gra-filing',
  path: '/gra-filing',
  getParentRoute: () => ComplianceRoute,
} as any)
const ComplianceAlertsRoute = ComplianceAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => ComplianceRoute,
} as any)
const ClientsNewRoute = ClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsActiveRoute = ClientsActiveRouteImport.update({
  id: '/clients/active',
  path: '/clients/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationTemplatesRoute = AutomationTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AutomationRoute,
} as any)
const AutomationRulesRoute = AutomationRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AutomationRoute,
} as any)
const AutomationHistoryRoute = AutomationHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AutomationRoute,
} as any)
const AppointmentsRequestsRoute = AppointmentsRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppointmentsRoute,
} as any)
const AppointmentsNewRoute = AppointmentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppointmentsRoute,
} as any)
const AppointmentsCalendarRoute = AppointmentsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppointmentsRoute,
} as any)
const AppointmentsIdRoute = AppointmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppointmentsRoute,
} as any)
const ClientsIdEditRoute = ClientsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ClientsIdRoute,
} as any)
const ClientsIdDocumentsRoute = ClientsIdDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ClientsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/automation': typeof AutomationRouteWithChildren
  '/compliance': typeof ComplianceRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/expediting': typeof ExpeditingRoute
  '/immigration': typeof ImmigrationRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/local-content': typeof LocalContentRoute
  '/login': typeof LoginRoute
  '/paralegal': typeof ParalegalRoute
  '/partner-network': typeof PartnerNetworkRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/profile': typeof ProfileRoute
  '/property-management': typeof PropertyManagementRoute
  '/service-catalog': typeof ServiceCatalogRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tax': typeof TaxRouteWithChildren
  '/time-tracking': typeof TimeTrackingRouteWithChildren
  '/training': typeof TrainingRoute
  '/users': typeof UsersRouteWithChildren
  '/appointments/$id': typeof AppointmentsIdRoute
  '/appointments/calendar': typeof AppointmentsCalendarRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/appointments/requests': typeof AppointmentsRequestsRoute
  '/automation/history': typeof AutomationHistoryRoute
  '/automation/rules': typeof AutomationRulesRoute
  '/automation/templates': typeof AutomationTemplatesRoute
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/clients/active': typeof ClientsActiveRoute
  '/clients/new': typeof ClientsNewRoute
  '/compliance/alerts': typeof ComplianceAlertsRoute
  '/compliance/gra-filing': typeof ComplianceGraFilingRoute
  '/compliance/reports': typeof ComplianceReportsRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/advanced': typeof DocumentsAdvancedRoute
  '/documents/requirements': typeof DocumentsRequirementsRoute
  '/documents/search': typeof DocumentsSearchRoute
  '/documents/templates': typeof DocumentsTemplatesRoute
  '/documents/upload': typeof DocumentsUploadRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/payments': typeof InvoicesPaymentsRoute
  '/payroll/employees': typeof PayrollEmployeesRoute
  '/payroll/reports': typeof PayrollReportsRoute
  '/payroll/run': typeof PayrollRunRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/filings': typeof PortalFilingsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tax/filing': typeof TaxFilingRoute
  '/tax/nis': typeof TaxNisRoute
  '/tax/paye': typeof TaxPayeRoute
  '/tax/vat': typeof TaxVatRoute
  '/time-tracking/entries': typeof TimeTrackingEntriesRoute
  '/time-tracking/projects': typeof TimeTrackingProjectsRoute
  '/time-tracking/reports': typeof TimeTrackingReportsRoute
  '/time-tracking/timer': typeof TimeTrackingTimerRoute
  '/users/invite': typeof UsersInviteRoute
  '/users/roles': typeof UsersRolesRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/automation/': typeof AutomationIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tax/': typeof TaxIndexRoute
  '/time-tracking/': typeof TimeTrackingIndexRoute
  '/users/': typeof UsersIndexRoute
  '/clients/$id/documents': typeof ClientsIdDocumentsRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/expediting': typeof ExpeditingRoute
  '/immigration': typeof ImmigrationRoute
  '/local-content': typeof LocalContentRoute
  '/login': typeof LoginRoute
  '/paralegal': typeof ParalegalRoute
  '/partner-network': typeof PartnerNetworkRoute
  '/profile': typeof ProfileRoute
  '/property-management': typeof PropertyManagementRoute
  '/service-catalog': typeof ServiceCatalogRoute
  '/training': typeof TrainingRoute
  '/appointments/$id': typeof AppointmentsIdRoute
  '/appointments/calendar': typeof AppointmentsCalendarRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/appointments/requests': typeof AppointmentsRequestsRoute
  '/automation/history': typeof AutomationHistoryRoute
  '/automation/rules': typeof AutomationRulesRoute
  '/automation/templates': typeof AutomationTemplatesRoute
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/clients/active': typeof ClientsActiveRoute
  '/clients/new': typeof ClientsNewRoute
  '/compliance/alerts': typeof ComplianceAlertsRoute
  '/compliance/gra-filing': typeof ComplianceGraFilingRoute
  '/compliance/reports': typeof ComplianceReportsRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/advanced': typeof DocumentsAdvancedRoute
  '/documents/requirements': typeof DocumentsRequirementsRoute
  '/documents/search': typeof DocumentsSearchRoute
  '/documents/templates': typeof DocumentsTemplatesRoute
  '/documents/upload': typeof DocumentsUploadRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/payments': typeof InvoicesPaymentsRoute
  '/payroll/employees': typeof PayrollEmployeesRoute
  '/payroll/reports': typeof PayrollReportsRoute
  '/payroll/run': typeof PayrollRunRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/filings': typeof PortalFilingsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tax/filing': typeof TaxFilingRoute
  '/tax/nis': typeof TaxNisRoute
  '/tax/paye': typeof TaxPayeRoute
  '/tax/vat': typeof TaxVatRoute
  '/time-tracking/entries': typeof TimeTrackingEntriesRoute
  '/time-tracking/projects': typeof TimeTrackingProjectsRoute
  '/time-tracking/reports': typeof TimeTrackingReportsRoute
  '/time-tracking/timer': typeof TimeTrackingTimerRoute
  '/users/invite': typeof UsersInviteRoute
  '/users/roles': typeof UsersRolesRoute
  '/appointments': typeof AppointmentsIndexRoute
  '/automation': typeof AutomationIndexRoute
  '/clients': typeof ClientsIndexRoute
  '/compliance': typeof ComplianceIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/payroll': typeof PayrollIndexRoute
  '/portal': typeof PortalIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/tax': typeof TaxIndexRoute
  '/time-tracking': typeof TimeTrackingIndexRoute
  '/users': typeof UsersIndexRoute
  '/clients/$id/documents': typeof ClientsIdDocumentsRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRouteWithChildren
  '/automation': typeof AutomationRouteWithChildren
  '/compliance': typeof ComplianceRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/expediting': typeof ExpeditingRoute
  '/immigration': typeof ImmigrationRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/local-content': typeof LocalContentRoute
  '/login': typeof LoginRoute
  '/paralegal': typeof ParalegalRoute
  '/partner-network': typeof PartnerNetworkRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/profile': typeof ProfileRoute
  '/property-management': typeof PropertyManagementRoute
  '/service-catalog': typeof ServiceCatalogRoute
  '/settings': typeof SettingsRouteWithChildren
  '/tax': typeof TaxRouteWithChildren
  '/time-tracking': typeof TimeTrackingRouteWithChildren
  '/training': typeof TrainingRoute
  '/users': typeof UsersRouteWithChildren
  '/appointments/$id': typeof AppointmentsIdRoute
  '/appointments/calendar': typeof AppointmentsCalendarRoute
  '/appointments/new': typeof AppointmentsNewRoute
  '/appointments/requests': typeof AppointmentsRequestsRoute
  '/automation/history': typeof AutomationHistoryRoute
  '/automation/rules': typeof AutomationRulesRoute
  '/automation/templates': typeof AutomationTemplatesRoute
  '/clients/$id': typeof ClientsIdRouteWithChildren
  '/clients/active': typeof ClientsActiveRoute
  '/clients/new': typeof ClientsNewRoute
  '/compliance/alerts': typeof ComplianceAlertsRoute
  '/compliance/gra-filing': typeof ComplianceGraFilingRoute
  '/compliance/reports': typeof ComplianceReportsRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/documents/advanced': typeof DocumentsAdvancedRoute
  '/documents/requirements': typeof DocumentsRequirementsRoute
  '/documents/search': typeof DocumentsSearchRoute
  '/documents/templates': typeof DocumentsTemplatesRoute
  '/documents/upload': typeof DocumentsUploadRoute
  '/invoices/$id': typeof InvoicesIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/invoices/payments': typeof InvoicesPaymentsRoute
  '/payroll/employees': typeof PayrollEmployeesRoute
  '/payroll/reports': typeof PayrollReportsRoute
  '/payroll/run': typeof PayrollRunRoute
  '/portal/appointments': typeof PortalAppointmentsRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/filings': typeof PortalFilingsRoute
  '/portal/payments': typeof PortalPaymentsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/backup': typeof SettingsBackupRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/tax/filing': typeof TaxFilingRoute
  '/tax/nis': typeof TaxNisRoute
  '/tax/paye': typeof TaxPayeRoute
  '/tax/vat': typeof TaxVatRoute
  '/time-tracking/entries': typeof TimeTrackingEntriesRoute
  '/time-tracking/projects': typeof TimeTrackingProjectsRoute
  '/time-tracking/reports': typeof TimeTrackingReportsRoute
  '/time-tracking/timer': typeof TimeTrackingTimerRoute
  '/users/invite': typeof UsersInviteRoute
  '/users/roles': typeof UsersRolesRoute
  '/appointments/': typeof AppointmentsIndexRoute
  '/automation/': typeof AutomationIndexRoute
  '/clients/': typeof ClientsIndexRoute
  '/compliance/': typeof ComplianceIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/tax/': typeof TaxIndexRoute
  '/time-tracking/': typeof TimeTrackingIndexRoute
  '/users/': typeof UsersIndexRoute
  '/clients/$id/documents': typeof ClientsIdDocumentsRoute
  '/clients/$id/edit': typeof ClientsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/automation'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/expediting'
    | '/immigration'
    | '/invoices'
    | '/local-content'
    | '/login'
    | '/paralegal'
    | '/partner-network'
    | '/payroll'
    | '/portal'
    | '/profile'
    | '/property-management'
    | '/service-catalog'
    | '/settings'
    | '/tax'
    | '/time-tracking'
    | '/training'
    | '/users'
    | '/appointments/$id'
    | '/appointments/calendar'
    | '/appointments/new'
    | '/appointments/requests'
    | '/automation/history'
    | '/automation/rules'
    | '/automation/templates'
    | '/clients/$id'
    | '/clients/active'
    | '/clients/new'
    | '/compliance/alerts'
    | '/compliance/gra-filing'
    | '/compliance/reports'
    | '/documents/$id'
    | '/documents/advanced'
    | '/documents/requirements'
    | '/documents/search'
    | '/documents/templates'
    | '/documents/upload'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices/payments'
    | '/payroll/employees'
    | '/payroll/reports'
    | '/payroll/run'
    | '/portal/appointments'
    | '/portal/documents'
    | '/portal/filings'
    | '/portal/payments'
    | '/portal/profile'
    | '/settings/appearance'
    | '/settings/backup'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/tax/filing'
    | '/tax/nis'
    | '/tax/paye'
    | '/tax/vat'
    | '/time-tracking/entries'
    | '/time-tracking/projects'
    | '/time-tracking/reports'
    | '/time-tracking/timer'
    | '/users/invite'
    | '/users/roles'
    | '/appointments/'
    | '/automation/'
    | '/clients'
    | '/compliance/'
    | '/documents/'
    | '/invoices/'
    | '/payroll/'
    | '/portal/'
    | '/settings/'
    | '/tax/'
    | '/time-tracking/'
    | '/users/'
    | '/clients/$id/documents'
    | '/clients/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/expediting'
    | '/immigration'
    | '/local-content'
    | '/login'
    | '/paralegal'
    | '/partner-network'
    | '/profile'
    | '/property-management'
    | '/service-catalog'
    | '/training'
    | '/appointments/$id'
    | '/appointments/calendar'
    | '/appointments/new'
    | '/appointments/requests'
    | '/automation/history'
    | '/automation/rules'
    | '/automation/templates'
    | '/clients/$id'
    | '/clients/active'
    | '/clients/new'
    | '/compliance/alerts'
    | '/compliance/gra-filing'
    | '/compliance/reports'
    | '/documents/$id'
    | '/documents/advanced'
    | '/documents/requirements'
    | '/documents/search'
    | '/documents/templates'
    | '/documents/upload'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices/payments'
    | '/payroll/employees'
    | '/payroll/reports'
    | '/payroll/run'
    | '/portal/appointments'
    | '/portal/documents'
    | '/portal/filings'
    | '/portal/payments'
    | '/portal/profile'
    | '/settings/appearance'
    | '/settings/backup'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/tax/filing'
    | '/tax/nis'
    | '/tax/paye'
    | '/tax/vat'
    | '/time-tracking/entries'
    | '/time-tracking/projects'
    | '/time-tracking/reports'
    | '/time-tracking/timer'
    | '/users/invite'
    | '/users/roles'
    | '/appointments'
    | '/automation'
    | '/clients'
    | '/compliance'
    | '/documents'
    | '/invoices'
    | '/payroll'
    | '/portal'
    | '/settings'
    | '/tax'
    | '/time-tracking'
    | '/users'
    | '/clients/$id/documents'
    | '/clients/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/automation'
    | '/compliance'
    | '/dashboard'
    | '/documents'
    | '/expediting'
    | '/immigration'
    | '/invoices'
    | '/local-content'
    | '/login'
    | '/paralegal'
    | '/partner-network'
    | '/payroll'
    | '/portal'
    | '/profile'
    | '/property-management'
    | '/service-catalog'
    | '/settings'
    | '/tax'
    | '/time-tracking'
    | '/training'
    | '/users'
    | '/appointments/$id'
    | '/appointments/calendar'
    | '/appointments/new'
    | '/appointments/requests'
    | '/automation/history'
    | '/automation/rules'
    | '/automation/templates'
    | '/clients/$id'
    | '/clients/active'
    | '/clients/new'
    | '/compliance/alerts'
    | '/compliance/gra-filing'
    | '/compliance/reports'
    | '/documents/$id'
    | '/documents/advanced'
    | '/documents/requirements'
    | '/documents/search'
    | '/documents/templates'
    | '/documents/upload'
    | '/invoices/$id'
    | '/invoices/new'
    | '/invoices/payments'
    | '/payroll/employees'
    | '/payroll/reports'
    | '/payroll/run'
    | '/portal/appointments'
    | '/portal/documents'
    | '/portal/filings'
    | '/portal/payments'
    | '/portal/profile'
    | '/settings/appearance'
    | '/settings/backup'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/security'
    | '/tax/filing'
    | '/tax/nis'
    | '/tax/paye'
    | '/tax/vat'
    | '/time-tracking/entries'
    | '/time-tracking/projects'
    | '/time-tracking/reports'
    | '/time-tracking/timer'
    | '/users/invite'
    | '/users/roles'
    | '/appointments/'
    | '/automation/'
    | '/clients/'
    | '/compliance/'
    | '/documents/'
    | '/invoices/'
    | '/payroll/'
    | '/portal/'
    | '/settings/'
    | '/tax/'
    | '/time-tracking/'
    | '/users/'
    | '/clients/$id/documents'
    | '/clients/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRouteWithChildren
  AutomationRoute: typeof AutomationRouteWithChildren
  ComplianceRoute: typeof ComplianceRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  ExpeditingRoute: typeof ExpeditingRoute
  ImmigrationRoute: typeof ImmigrationRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LocalContentRoute: typeof LocalContentRoute
  LoginRoute: typeof LoginRoute
  ParalegalRoute: typeof ParalegalRoute
  PartnerNetworkRoute: typeof PartnerNetworkRoute
  PayrollRoute: typeof PayrollRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  PropertyManagementRoute: typeof PropertyManagementRoute
  ServiceCatalogRoute: typeof ServiceCatalogRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  TaxRoute: typeof TaxRouteWithChildren
  TimeTrackingRoute: typeof TimeTrackingRouteWithChildren
  TrainingRoute: typeof TrainingRoute
  UsersRoute: typeof UsersRouteWithChildren
  ClientsIdRoute: typeof ClientsIdRouteWithChildren
  ClientsActiveRoute: typeof ClientsActiveRoute
  ClientsNewRoute: typeof ClientsNewRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-tracking': {
      id: '/time-tracking'
      path: '/time-tracking'
      fullPath: '/time-tracking'
      preLoaderRoute: typeof TimeTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tax': {
      id: '/tax'
      path: '/tax'
      fullPath: '/tax'
      preLoaderRoute: typeof TaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-catalog': {
      id: '/service-catalog'
      path: '/service-catalog'
      fullPath: '/service-catalog'
      preLoaderRoute: typeof ServiceCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property-management': {
      id: '/property-management'
      path: '/property-management'
      fullPath: '/property-management'
      preLoaderRoute: typeof PropertyManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-network': {
      id: '/partner-network'
      path: '/partner-network'
      fullPath: '/partner-network'
      preLoaderRoute: typeof PartnerNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paralegal': {
      id: '/paralegal'
      path: '/paralegal'
      fullPath: '/paralegal'
      preLoaderRoute: typeof ParalegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local-content': {
      id: '/local-content'
      path: '/local-content'
      fullPath: '/local-content'
      preLoaderRoute: typeof LocalContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immigration': {
      id: '/immigration'
      path: '/immigration'
      fullPath: '/immigration'
      preLoaderRoute: typeof ImmigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expediting': {
      id: '/expediting'
      path: '/expediting'
      fullPath: '/expediting'
      preLoaderRoute: typeof ExpeditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof UsersRoute
    }
    '/time-tracking/': {
      id: '/time-tracking/'
      path: '/'
      fullPath: '/time-tracking/'
      preLoaderRoute: typeof TimeTrackingIndexRouteImport
      parentRoute: typeof TimeTrackingRoute
    }
    '/tax/': {
      id: '/tax/'
      path: '/'
      fullPath: '/tax/'
      preLoaderRoute: typeof TaxIndexRouteImport
      parentRoute: typeof TaxRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/compliance/': {
      id: '/compliance/'
      path: '/'
      fullPath: '/compliance/'
      preLoaderRoute: typeof ComplianceIndexRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/': {
      id: '/automation/'
      path: '/'
      fullPath: '/automation/'
      preLoaderRoute: typeof AutomationIndexRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/appointments/': {
      id: '/appointments/'
      path: '/'
      fullPath: '/appointments/'
      preLoaderRoute: typeof AppointmentsIndexRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/users/roles': {
      id: '/users/roles'
      path: '/roles'
      fullPath: '/users/roles'
      preLoaderRoute: typeof UsersRolesRouteImport
      parentRoute: typeof UsersRoute
    }
    '/users/invite': {
      id: '/users/invite'
      path: '/invite'
      fullPath: '/users/invite'
      preLoaderRoute: typeof UsersInviteRouteImport
      parentRoute: typeof UsersRoute
    }
    '/time-tracking/timer': {
      id: '/time-tracking/timer'
      path: '/timer'
      fullPath: '/time-tracking/timer'
      preLoaderRoute: typeof TimeTrackingTimerRouteImport
      parentRoute: typeof TimeTrackingRoute
    }
    '/time-tracking/reports': {
      id: '/time-tracking/reports'
      path: '/reports'
      fullPath: '/time-tracking/reports'
      preLoaderRoute: typeof TimeTrackingReportsRouteImport
      parentRoute: typeof TimeTrackingRoute
    }
    '/time-tracking/projects': {
      id: '/time-tracking/projects'
      path: '/projects'
      fullPath: '/time-tracking/projects'
      preLoaderRoute: typeof TimeTrackingProjectsRouteImport
      parentRoute: typeof TimeTrackingRoute
    }
    '/time-tracking/entries': {
      id: '/time-tracking/entries'
      path: '/entries'
      fullPath: '/time-tracking/entries'
      preLoaderRoute: typeof TimeTrackingEntriesRouteImport
      parentRoute: typeof TimeTrackingRoute
    }
    '/tax/vat': {
      id: '/tax/vat'
      path: '/vat'
      fullPath: '/tax/vat'
      preLoaderRoute: typeof TaxVatRouteImport
      parentRoute: typeof TaxRoute
    }
    '/tax/paye': {
      id: '/tax/paye'
      path: '/paye'
      fullPath: '/tax/paye'
      preLoaderRoute: typeof TaxPayeRouteImport
      parentRoute: typeof TaxRoute
    }
    '/tax/nis': {
      id: '/tax/nis'
      path: '/nis'
      fullPath: '/tax/nis'
      preLoaderRoute: typeof TaxNisRouteImport
      parentRoute: typeof TaxRoute
    }
    '/tax/filing': {
      id: '/tax/filing'
      path: '/filing'
      fullPath: '/tax/filing'
      preLoaderRoute: typeof TaxFilingRouteImport
      parentRoute: typeof TaxRoute
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/backup': {
      id: '/settings/backup'
      path: '/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof SettingsBackupRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/payments': {
      id: '/portal/payments'
      path: '/payments'
      fullPath: '/portal/payments'
      preLoaderRoute: typeof PortalPaymentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/filings': {
      id: '/portal/filings'
      path: '/filings'
      fullPath: '/portal/filings'
      preLoaderRoute: typeof PortalFilingsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/appointments': {
      id: '/portal/appointments'
      path: '/appointments'
      fullPath: '/portal/appointments'
      preLoaderRoute: typeof PortalAppointmentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/payroll/run': {
      id: '/payroll/run'
      path: '/run'
      fullPath: '/payroll/run'
      preLoaderRoute: typeof PayrollRunRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/reports': {
      id: '/payroll/reports'
      path: '/reports'
      fullPath: '/payroll/reports'
      preLoaderRoute: typeof PayrollReportsRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/employees': {
      id: '/payroll/employees'
      path: '/employees'
      fullPath: '/payroll/employees'
      preLoaderRoute: typeof PayrollEmployeesRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/invoices/payments': {
      id: '/invoices/payments'
      path: '/payments'
      fullPath: '/invoices/payments'
      preLoaderRoute: typeof InvoicesPaymentsRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/documents/upload': {
      id: '/documents/upload'
      path: '/upload'
      fullPath: '/documents/upload'
      preLoaderRoute: typeof DocumentsUploadRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/templates': {
      id: '/documents/templates'
      path: '/templates'
      fullPath: '/documents/templates'
      preLoaderRoute: typeof DocumentsTemplatesRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/search': {
      id: '/documents/search'
      path: '/search'
      fullPath: '/documents/search'
      preLoaderRoute: typeof DocumentsSearchRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/requirements': {
      id: '/documents/requirements'
      path: '/requirements'
      fullPath: '/documents/requirements'
      preLoaderRoute: typeof DocumentsRequirementsRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/advanced': {
      id: '/documents/advanced'
      path: '/advanced'
      fullPath: '/documents/advanced'
      preLoaderRoute: typeof DocumentsAdvancedRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/compliance/reports': {
      id: '/compliance/reports'
      path: '/reports'
      fullPath: '/compliance/reports'
      preLoaderRoute: typeof ComplianceReportsRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/compliance/gra-filing': {
      id: '/compliance/gra-filing'
      path: '/gra-filing'
      fullPath: '/compliance/gra-filing'
      preLoaderRoute: typeof ComplianceGraFilingRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/compliance/alerts': {
      id: '/compliance/alerts'
      path: '/alerts'
      fullPath: '/compliance/alerts'
      preLoaderRoute: typeof ComplianceAlertsRouteImport
      parentRoute: typeof ComplianceRoute
    }
    '/clients/new': {
      id: '/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof ClientsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/active': {
      id: '/clients/active'
      path: '/clients/active'
      fullPath: '/clients/active'
      preLoaderRoute: typeof ClientsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/templates': {
      id: '/automation/templates'
      path: '/templates'
      fullPath: '/automation/templates'
      preLoaderRoute: typeof AutomationTemplatesRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/automation/rules': {
      id: '/automation/rules'
      path: '/rules'
      fullPath: '/automation/rules'
      preLoaderRoute: typeof AutomationRulesRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/automation/history': {
      id: '/automation/history'
      path: '/history'
      fullPath: '/automation/history'
      preLoaderRoute: typeof AutomationHistoryRouteImport
      parentRoute: typeof AutomationRoute
    }
    '/appointments/requests': {
      id: '/appointments/requests'
      path: '/requests'
      fullPath: '/appointments/requests'
      preLoaderRoute: typeof AppointmentsRequestsRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/appointments/new': {
      id: '/appointments/new'
      path: '/new'
      fullPath: '/appointments/new'
      preLoaderRoute: typeof AppointmentsNewRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/appointments/calendar': {
      id: '/appointments/calendar'
      path: '/calendar'
      fullPath: '/appointments/calendar'
      preLoaderRoute: typeof AppointmentsCalendarRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/appointments/$id': {
      id: '/appointments/$id'
      path: '/$id'
      fullPath: '/appointments/$id'
      preLoaderRoute: typeof AppointmentsIdRouteImport
      parentRoute: typeof AppointmentsRoute
    }
    '/clients/$id/edit': {
      id: '/clients/$id/edit'
      path: '/edit'
      fullPath: '/clients/$id/edit'
      preLoaderRoute: typeof ClientsIdEditRouteImport
      parentRoute: typeof ClientsIdRoute
    }
    '/clients/$id/documents': {
      id: '/clients/$id/documents'
      path: '/documents'
      fullPath: '/clients/$id/documents'
      preLoaderRoute: typeof ClientsIdDocumentsRouteImport
      parentRoute: typeof ClientsIdRoute
    }
  }
}

interface AppointmentsRouteChildren {
  AppointmentsIdRoute: typeof AppointmentsIdRoute
  AppointmentsCalendarRoute: typeof AppointmentsCalendarRoute
  AppointmentsNewRoute: typeof AppointmentsNewRoute
  AppointmentsRequestsRoute: typeof AppointmentsRequestsRoute
  AppointmentsIndexRoute: typeof AppointmentsIndexRoute
}

const AppointmentsRouteChildren: AppointmentsRouteChildren = {
  AppointmentsIdRoute: AppointmentsIdRoute,
  AppointmentsCalendarRoute: AppointmentsCalendarRoute,
  AppointmentsNewRoute: AppointmentsNewRoute,
  AppointmentsRequestsRoute: AppointmentsRequestsRoute,
  AppointmentsIndexRoute: AppointmentsIndexRoute,
}

const AppointmentsRouteWithChildren = AppointmentsRoute._addFileChildren(
  AppointmentsRouteChildren,
)

interface AutomationRouteChildren {
  AutomationHistoryRoute: typeof AutomationHistoryRoute
  AutomationRulesRoute: typeof AutomationRulesRoute
  AutomationTemplatesRoute: typeof AutomationTemplatesRoute
  AutomationIndexRoute: typeof AutomationIndexRoute
}

const AutomationRouteChildren: AutomationRouteChildren = {
  AutomationHistoryRoute: AutomationHistoryRoute,
  AutomationRulesRoute: AutomationRulesRoute,
  AutomationTemplatesRoute: AutomationTemplatesRoute,
  AutomationIndexRoute: AutomationIndexRoute,
}

const AutomationRouteWithChildren = AutomationRoute._addFileChildren(
  AutomationRouteChildren,
)

interface ComplianceRouteChildren {
  ComplianceAlertsRoute: typeof ComplianceAlertsRoute
  ComplianceGraFilingRoute: typeof ComplianceGraFilingRoute
  ComplianceReportsRoute: typeof ComplianceReportsRoute
  ComplianceIndexRoute: typeof ComplianceIndexRoute
}

const ComplianceRouteChildren: ComplianceRouteChildren = {
  ComplianceAlertsRoute: ComplianceAlertsRoute,
  ComplianceGraFilingRoute: ComplianceGraFilingRoute,
  ComplianceReportsRoute: ComplianceReportsRoute,
  ComplianceIndexRoute: ComplianceIndexRoute,
}

const ComplianceRouteWithChildren = ComplianceRoute._addFileChildren(
  ComplianceRouteChildren,
)

interface DocumentsRouteChildren {
  DocumentsIdRoute: typeof DocumentsIdRoute
  DocumentsAdvancedRoute: typeof DocumentsAdvancedRoute
  DocumentsRequirementsRoute: typeof DocumentsRequirementsRoute
  DocumentsSearchRoute: typeof DocumentsSearchRoute
  DocumentsTemplatesRoute: typeof DocumentsTemplatesRoute
  DocumentsUploadRoute: typeof DocumentsUploadRoute
  DocumentsIndexRoute: typeof DocumentsIndexRoute
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsIdRoute: DocumentsIdRoute,
  DocumentsAdvancedRoute: DocumentsAdvancedRoute,
  DocumentsRequirementsRoute: DocumentsRequirementsRoute,
  DocumentsSearchRoute: DocumentsSearchRoute,
  DocumentsTemplatesRoute: DocumentsTemplatesRoute,
  DocumentsUploadRoute: DocumentsUploadRoute,
  DocumentsIndexRoute: DocumentsIndexRoute,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
  InvoicesNewRoute: typeof InvoicesNewRoute
  InvoicesPaymentsRoute: typeof InvoicesPaymentsRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
  InvoicesNewRoute: InvoicesNewRoute,
  InvoicesPaymentsRoute: InvoicesPaymentsRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface PayrollRouteChildren {
  PayrollEmployeesRoute: typeof PayrollEmployeesRoute
  PayrollReportsRoute: typeof PayrollReportsRoute
  PayrollRunRoute: typeof PayrollRunRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
}

const PayrollRouteChildren: PayrollRouteChildren = {
  PayrollEmployeesRoute: PayrollEmployeesRoute,
  PayrollReportsRoute: PayrollReportsRoute,
  PayrollRunRoute: PayrollRunRoute,
  PayrollIndexRoute: PayrollIndexRoute,
}

const PayrollRouteWithChildren =
  PayrollRoute._addFileChildren(PayrollRouteChildren)

interface PortalRouteChildren {
  PortalAppointmentsRoute: typeof PortalAppointmentsRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalFilingsRoute: typeof PortalFilingsRoute
  PortalPaymentsRoute: typeof PortalPaymentsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAppointmentsRoute: PortalAppointmentsRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalFilingsRoute: PortalFilingsRoute,
  PortalPaymentsRoute: PortalPaymentsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsBackupRoute: typeof SettingsBackupRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsBackupRoute: SettingsBackupRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface TaxRouteChildren {
  TaxFilingRoute: typeof TaxFilingRoute
  TaxNisRoute: typeof TaxNisRoute
  TaxPayeRoute: typeof TaxPayeRoute
  TaxVatRoute: typeof TaxVatRoute
  TaxIndexRoute: typeof TaxIndexRoute
}

const TaxRouteChildren: TaxRouteChildren = {
  TaxFilingRoute: TaxFilingRoute,
  TaxNisRoute: TaxNisRoute,
  TaxPayeRoute: TaxPayeRoute,
  TaxVatRoute: TaxVatRoute,
  TaxIndexRoute: TaxIndexRoute,
}

const TaxRouteWithChildren = TaxRoute._addFileChildren(TaxRouteChildren)

interface TimeTrackingRouteChildren {
  TimeTrackingEntriesRoute: typeof TimeTrackingEntriesRoute
  TimeTrackingProjectsRoute: typeof TimeTrackingProjectsRoute
  TimeTrackingReportsRoute: typeof TimeTrackingReportsRoute
  TimeTrackingTimerRoute: typeof TimeTrackingTimerRoute
  TimeTrackingIndexRoute: typeof TimeTrackingIndexRoute
}

const TimeTrackingRouteChildren: TimeTrackingRouteChildren = {
  TimeTrackingEntriesRoute: TimeTrackingEntriesRoute,
  TimeTrackingProjectsRoute: TimeTrackingProjectsRoute,
  TimeTrackingReportsRoute: TimeTrackingReportsRoute,
  TimeTrackingTimerRoute: TimeTrackingTimerRoute,
  TimeTrackingIndexRoute: TimeTrackingIndexRoute,
}

const TimeTrackingRouteWithChildren = TimeTrackingRoute._addFileChildren(
  TimeTrackingRouteChildren,
)

interface UsersRouteChildren {
  UsersInviteRoute: typeof UsersInviteRoute
  UsersRolesRoute: typeof UsersRolesRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

const UsersRouteChildren: UsersRouteChildren = {
  UsersInviteRoute: UsersInviteRoute,
  UsersRolesRoute: UsersRolesRoute,
  UsersIndexRoute: UsersIndexRoute,
}

const UsersRouteWithChildren = UsersRoute._addFileChildren(UsersRouteChildren)

interface ClientsIdRouteChildren {
  ClientsIdDocumentsRoute: typeof ClientsIdDocumentsRoute
  ClientsIdEditRoute: typeof ClientsIdEditRoute
}

const ClientsIdRouteChildren: ClientsIdRouteChildren = {
  ClientsIdDocumentsRoute: ClientsIdDocumentsRoute,
  ClientsIdEditRoute: ClientsIdEditRoute,
}

const ClientsIdRouteWithChildren = ClientsIdRoute._addFileChildren(
  ClientsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRouteWithChildren,
  AutomationRoute: AutomationRouteWithChildren,
  ComplianceRoute: ComplianceRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  ExpeditingRoute: ExpeditingRoute,
  ImmigrationRoute: ImmigrationRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LocalContentRoute: LocalContentRoute,
  LoginRoute: LoginRoute,
  ParalegalRoute: ParalegalRoute,
  PartnerNetworkRoute: PartnerNetworkRoute,
  PayrollRoute: PayrollRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  ProfileRoute: ProfileRoute,
  PropertyManagementRoute: PropertyManagementRoute,
  ServiceCatalogRoute: ServiceCatalogRoute,
  SettingsRoute: SettingsRouteWithChildren,
  TaxRoute: TaxRouteWithChildren,
  TimeTrackingRoute: TimeTrackingRouteWithChildren,
  TrainingRoute: TrainingRoute,
  UsersRoute: UsersRouteWithChildren,
  ClientsIdRoute: ClientsIdRouteWithChildren,
  ClientsActiveRoute: ClientsActiveRoute,
  ClientsNewRoute: ClientsNewRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
