import type { RouterClient } from "@orpc/server";
import { protectedProcedure, publicProcedure } from "../index";
// AI (FLAT procedures)
import {
  aiClassifyDocument,
  aiExecuteSmartFiling,
  aiExecuteSmartIntegration,
  aiGenerateClientInsights,
  aiGenerateExecutiveSummary,
  aiGenerateRealTimeInsights,
  aiGetBusinessMetrics,
  aiGetClientInsightsDashboard,
  aiGetSystemHealth,
  aiGetTaxSeasonAnalytics,
  aiGetUsageMetrics,
  aiManageMLModels,
  aiMonitorCompliance,
  aiPerformRiskAssessment,
  aiPerformSmartSubmission,
  aiProcessDocumentsIntelligently,
  aiValidateSubmissionData,
  aiValidateTaxCalculation,
} from "./ai";
// Appointments (FLAT procedures)
import {
  appointmentCancel,
  appointmentCheckAvailability,
  appointmentCreate,
  appointmentCreateExternal,
  appointmentGetById,
  appointmentGetStats,
  appointmentList,
  appointmentReschedule,
  appointmentUpdate,
} from "./appointments";
// Audit (FLAT procedures)
import {
  auditArchiveLogs,
  auditCreateSystemEvent,
  auditExportLogs,
  auditGenerateComplianceReport,
  auditGetLogById,
  auditGetRetentionPolicy,
  auditGetSummary,
  auditGetSuspiciousActivity,
  auditListLoginAttempts,
  auditListSystemEvents,
  auditSearchLogs,
} from "./audit";
// Backup (FLAT procedures)
import {
  backupCreate,
  backupCreateSchedule,
  backupDelete,
  backupDeleteSchedule,
  backupExportSettings,
  backupGetAuditLog,
  backupGetById,
  backupGetStorageStats,
  backupList,
  backupListRestoreOperations,
  backupListSchedules,
  backupRestore,
  backupUpdateSchedule,
  backupVerify,
} from "./backup";
// Clients (FLAT procedures)
import {
  clientBulkAction,
  clientContactCreate,
  clientContactDelete,
  clientContactList,
  clientContactUpdate,
  clientCreate,
  clientDelete,
  clientGetById,
  clientGetImmigrationStatus,
  clientGetImmigrationWorkflowTemplates,
  clientList,
  clientServiceCreate,
  clientServiceDelete,
  clientServiceList,
  clientServiceUpdate,
  clientStats,
  clientSubmitImmigrationDocuments,
  clientUpdate,
  clientUpdateImmigrationStatus,
  clientWizardComplete,
  clientWizardStep1,
  clientWizardStep2,
  clientWizardStep3,
  clientWizardStep4,
} from "./clients";
// Compliance (FLAT procedures)
import {
  complianceCreateFiling,
  complianceCreateRequirement,
  complianceExportGraForm7B,
  complianceGetAlerts,
  complianceGetAuditTrail,
  complianceGetDashboardOverview,
  complianceGetFilings,
  complianceGetRequirements,
  complianceUpdateFiling,
  complianceUpdateRequirement,
} from "./compliance";
// Dashboard (FLAT procedures)
import {
  dashboardClientPerformance,
  dashboardComplianceReport,
  dashboardFinancialSummary,
  dashboardKpis,
  dashboardOverview,
  dashboardRevenueAnalysis,
} from "./dashboard";
// Documents (FLAT procedures)
import {
  documentCreate,
  documentCreateFolder,
  documentCreateVersion,
  documentDelete,
  documentGetById,
  documentGetStats,
  documentGetVersions,
  documentList,
  documentListFolders,
  documentMoveDocument,
  documentRequirementChecklists,
  documentRequirementList,
  documentRequirementServiceTypes,
  documentSearch,
  documentShare,
  documentTemplateCategories,
  documentTemplateGetById,
  documentTemplateList,
  documentUpdate,
} from "./documents";
// Expediting (FLAT procedures)
import {
  expeditingActivitiesCreate,
  expeditingActivitiesList,
  expeditingAgencyContactsCreate,
  expeditingAgencyContactsList,
  expeditingAgencyContactsUpdate,
  expeditingQueueCreate,
  expeditingQueueList,
  expeditingQueueUpdateStatus,
  expeditingRequestsAssign,
  expeditingRequestsComplete,
  expeditingRequestsCreate,
  expeditingRequestsGetById,
  expeditingRequestsList,
  expeditingRequestsStats,
  expeditingRequestsUpdate,
} from "./expediting";
// GRA Integration (FLAT procedures)
import {
  graAuthenticate,
  graCheckSubmissionStatus,
  graExportClientData,
  graGetFilingCalendar,
  graSubmitFiling,
  graSyncClient,
} from "./gra-integration";
// Immigration (FLAT procedures)
import {
  immigrationArchiveCase,
  immigrationCreateCase,
  immigrationCreateDocumentRequirement,
  immigrationCreateTimelineEvent,
  immigrationGetCaseById,
  immigrationGetCaseTimeline,
  immigrationGetDocumentRequirements,
  immigrationGetStats,
  immigrationGetUpcomingDeadlines,
  immigrationListCases,
  immigrationUpdateCase,
  immigrationUpdateDocumentRequirement,
} from "./immigration";
// Invoices (FLAT procedures)
import {
  invoiceCreate,
  invoiceDelete,
  invoiceGetById,
  invoiceList,
  invoiceStats,
  invoiceUpdate,
} from "./invoices";
// Local Content (FLAT procedures)
import {
  localContentChecklistsCreate,
  localContentChecklistsList,
  localContentChecklistsUpdateItem,
  localContentPlansCreate,
  localContentPlansList,
  localContentPlansSubmit,
  localContentPlansUpdate,
  localContentRegistrationsApprove,
  localContentRegistrationsCreate,
  localContentRegistrationsGetById,
  localContentRegistrationsList,
  localContentRegistrationsStats,
  localContentRegistrationsUpdate,
  localContentReportsCreate,
  localContentReportsList,
  localContentReportsSubmit,
  localContentReportsUpdate,
  localContentVendorsCreate,
  localContentVendorsList,
  localContentVendorsUpdate,
} from "./local-content";
// Notifications (FLAT procedures)
import {
  notificationArchive,
  notificationBulkMarkRead,
  notificationCreate,
  notificationCreateTemplate,
  notificationGetMine,
  notificationGetPreferences,
  notificationGetStats,
  notificationGetTemplates,
  notificationMarkAllRead,
  notificationMarkRead,
  notificationUpdatePreferences,
} from "./notifications";
// OCR (FLAT procedures)
import {
  ocrBatchProcess,
  ocrGetBatchStatus,
  ocrGetExtractedData,
  ocrGetProcessingStats,
  ocrGetProcessingStatus,
  ocrProcessDocument,
  ocrValidateResults,
} from "./ocr";
// Partner Network (FLAT procedures)
import {
  partnerNetworkAgreementsActivate,
  partnerNetworkAgreementsCreate,
  partnerNetworkAgreementsDelete,
  partnerNetworkAgreementsGetById,
  partnerNetworkAgreementsList,
  partnerNetworkAgreementsUpdate,
  partnerNetworkCommunicationsCreate,
  partnerNetworkCommunicationsDelete,
  partnerNetworkCommunicationsGetById,
  partnerNetworkCommunicationsGetPendingFollowUps,
  partnerNetworkCommunicationsList,
  partnerNetworkCommunicationsMarkFollowUpComplete,
  partnerNetworkPartnersCreate,
  partnerNetworkPartnersDelete,
  partnerNetworkPartnersGetById,
  partnerNetworkPartnersList,
  partnerNetworkPartnersStats,
  partnerNetworkPartnersUpdate,
  partnerNetworkPartnersUpdateTier,
  partnerNetworkPartnersVerify,
  partnerNetworkReferralsAccept,
  partnerNetworkReferralsComplete,
  partnerNetworkReferralsCreate,
  partnerNetworkReferralsDelete,
  partnerNetworkReferralsGetById,
  partnerNetworkReferralsList,
  partnerNetworkReferralsUpdate,
  partnerNetworkReviewsAddResponse,
  partnerNetworkReviewsCreate,
  partnerNetworkReviewsDelete,
  partnerNetworkReviewsGetById,
  partnerNetworkReviewsList,
  partnerNetworkReviewsModerate,
} from "./partner-network";
// Payroll (FLAT procedures)
import {
  payrollCalculate,
  payrollDepartments,
  payrollEmployeeCreate,
  payrollEmployeeDelete,
  payrollEmployeeGetById,
  payrollEmployeeList,
  payrollEmployeeUpdate,
  payrollRunsCreate,
  payrollRunsList,
} from "./payroll";
// Property Management (FLAT procedures)
import {
  propertyManagementInspectionsComplete,
  propertyManagementInspectionsCreate,
  propertyManagementInspectionsList,
  propertyManagementLeasesCreate,
  propertyManagementLeasesGetById,
  propertyManagementLeasesGetExpiring,
  propertyManagementLeasesList,
  propertyManagementLeasesTerminate,
  propertyManagementLeasesUpdate,
  propertyManagementMaintenanceCreate,
  propertyManagementMaintenanceList,
  propertyManagementMaintenanceUpdate,
  propertyManagementPaymentsGetOverdue,
  propertyManagementPaymentsList,
  propertyManagementPaymentsRecordPayment,
  propertyManagementPaymentsUpdatePayment,
  propertyManagementPropertiesCreate,
  propertyManagementPropertiesDelete,
  propertyManagementPropertiesGetById,
  propertyManagementPropertiesList,
  propertyManagementPropertiesStats,
  propertyManagementPropertiesUpdate,
  propertyManagementTenantsCreate,
  propertyManagementTenantsDelete,
  propertyManagementTenantsGetById,
  propertyManagementTenantsList,
  propertyManagementTenantsUpdate,
} from "./property-management";
// RBAC (FLAT procedures)
import {
  rbacAssignRoleToUser,
  rbacCheckPermission,
  rbacCreatePermission,
  rbacCreateRole,
  rbacDenyPermissionToUser,
  rbacGetUserPermissions,
  rbacGrantPermissionToUser,
  rbacListPermissions,
  rbacListRoles,
  rbacRemoveRoleFromUser,
} from "./rbac";
// Service Catalog (spread - already flat internally)
import { serviceCatalogRouter } from "./service-catalog";
// Tax (FLAT procedures)
import {
  taxCalculateNis,
  taxCalculatePaye,
  taxCalculatePayroll,
  taxCalculateQuarterly,
  taxCalculateVat,
  taxCheckVatRegistration,
  taxFilingsList,
  taxGenerateGraForm,
  taxGetCalculationHistory,
  taxGetDeadlines,
  taxGetRates,
  taxGetSubmissionStatus,
  taxGetSummary,
  taxSaveCalculation,
  taxSubmitCorporateTaxReturn,
  taxSubmitPayeReturn,
  taxSubmitVatReturn,
} from "./tax";
// Training (FLAT procedures)
import {
  trainingCertificatesIssue,
  trainingCertificatesList,
  trainingCertificatesVerify,
  trainingCoursesCreate,
  trainingCoursesGetById,
  trainingCoursesList,
  trainingCoursesPublish,
  trainingCoursesStats,
  trainingCoursesUpdate,
  trainingInstructorsCreate,
  trainingInstructorsList,
  trainingInstructorsUpdate,
  trainingRegistrationsCreate,
  trainingRegistrationsList,
  trainingRegistrationsMarkAttendance,
  trainingRegistrationsUpdateStatus,
  trainingSessionsCreate,
  trainingSessionsGetById,
  trainingSessionsList,
  trainingSessionsOpenRegistration,
  trainingSessionsUpdate,
} from "./training";
// Users (FLAT procedures)
import {
  userBulkAction,
  userChangePassword,
  userCreate,
  userDelete,
  userGetById,
  userList,
  userMe,
  userResetPassword,
  userRolesAndPermissions,
  userStats,
  userUpdate,
  userUpdatePermissions,
} from "./users";

export const appRouter = {
  healthCheck: publicProcedure.handler(() => "OK"),
  privateData: protectedProcedure.handler(({ context }) => ({
    message: "This is private",
    user: context.user,
  })),

  // AI (FLAT procedures)
  aiClassifyDocument,
  aiValidateTaxCalculation,
  aiPerformRiskAssessment,
  aiGenerateClientInsights,
  aiMonitorCompliance,
  aiPerformSmartSubmission,
  aiValidateSubmissionData,
  aiGetBusinessMetrics,
  aiGetTaxSeasonAnalytics,
  aiGetClientInsightsDashboard,
  aiGenerateExecutiveSummary,
  aiExecuteSmartIntegration,
  aiProcessDocumentsIntelligently,
  aiExecuteSmartFiling,
  aiGenerateRealTimeInsights,
  aiManageMLModels,
  aiGetSystemHealth,
  aiGetUsageMetrics,

  // Backup (FLAT procedures)
  backupCreate,
  backupList,
  backupGetById,
  backupDelete,
  backupVerify,
  backupRestore,
  backupCreateSchedule,
  backupListSchedules,
  backupUpdateSchedule,
  backupDeleteSchedule,
  backupGetStorageStats,
  backupListRestoreOperations,
  backupExportSettings,
  backupGetAuditLog,

  // Audit (FLAT procedures)
  auditSearchLogs,
  auditGetLogById,
  auditExportLogs,
  auditGetSummary,
  auditArchiveLogs,
  auditListSystemEvents,
  auditCreateSystemEvent,
  auditListLoginAttempts,
  auditGetSuspiciousActivity,
  auditGenerateComplianceReport,
  auditGetRetentionPolicy,

  // RBAC (FLAT procedures)
  rbacCheckPermission,
  rbacGetUserPermissions,
  rbacListRoles,
  rbacCreateRole,
  rbacAssignRoleToUser,
  rbacRemoveRoleFromUser,
  rbacListPermissions,
  rbacCreatePermission,
  rbacGrantPermissionToUser,
  rbacDenyPermissionToUser,

  // Clients (FLAT procedures)
  clientGetImmigrationStatus,
  clientUpdateImmigrationStatus,
  clientSubmitImmigrationDocuments,
  clientGetImmigrationWorkflowTemplates,
  clientList,
  clientGetById,
  clientCreate,
  clientUpdate,
  clientDelete,
  clientWizardStep1,
  clientWizardStep2,
  clientWizardStep3,
  clientWizardStep4,
  clientWizardComplete,
  clientContactList,
  clientContactCreate,
  clientContactUpdate,
  clientContactDelete,
  clientServiceList,
  clientServiceCreate,
  clientServiceUpdate,
  clientServiceDelete,
  clientBulkAction,
  clientStats,

  // Users (FLAT procedures)
  userList,
  userGetById,
  userMe,
  userCreate,
  userUpdate,
  userDelete,
  userChangePassword,
  userResetPassword,
  userUpdatePermissions,
  userBulkAction,
  userStats,
  userRolesAndPermissions,

  // Tax (FLAT procedures)
  taxSubmitVatReturn,
  taxSubmitPayeReturn,
  taxSubmitCorporateTaxReturn,
  taxGetSubmissionStatus,
  taxGetDeadlines,
  taxCalculatePaye,
  taxCalculateNis,
  taxCalculateVat,
  taxCalculatePayroll,
  taxCalculateQuarterly,
  taxCheckVatRegistration,
  taxGenerateGraForm,
  taxSaveCalculation,
  taxGetCalculationHistory,
  taxGetSummary,
  taxGetRates,
  taxFilingsList,

  // Payroll (FLAT procedures)
  payrollEmployeeList,
  payrollEmployeeGetById,
  payrollEmployeeCreate,
  payrollEmployeeUpdate,
  payrollEmployeeDelete,
  payrollCalculate,
  payrollRunsList,
  payrollRunsCreate,
  payrollDepartments,

  // Invoices (FLAT procedures)
  invoiceList,
  invoiceGetById,
  invoiceCreate,
  invoiceUpdate,
  invoiceDelete,
  invoiceStats,

  // Dashboard (FLAT procedures)
  dashboardOverview,
  dashboardKpis,
  dashboardRevenueAnalysis,
  dashboardComplianceReport,
  dashboardClientPerformance,
  dashboardFinancialSummary,

  // Documents (FLAT procedures)
  documentCreate,
  documentList,
  documentGetVersions,
  documentGetById,
  documentUpdate,
  documentCreateVersion,
  documentDelete,
  documentShare,
  documentCreateFolder,
  documentListFolders,
  documentMoveDocument,
  documentGetStats,
  documentSearch,
  documentTemplateList,
  documentTemplateGetById,
  documentTemplateCategories,
  documentRequirementList,
  documentRequirementServiceTypes,
  documentRequirementChecklists,

  // Compliance (FLAT procedures)
  complianceGetDashboardOverview,
  complianceGetRequirements,
  complianceGetFilings,
  complianceCreateRequirement,
  complianceUpdateRequirement,
  complianceCreateFiling,
  complianceUpdateFiling,
  complianceExportGraForm7B,
  complianceGetAlerts,
  complianceGetAuditTrail,

  // Appointments (FLAT procedures)
  appointmentCreate,
  appointmentCreateExternal,
  appointmentList,
  appointmentGetById,
  appointmentUpdate,
  appointmentCancel,
  appointmentReschedule,
  appointmentCheckAvailability,
  appointmentGetStats,

  // Notifications (FLAT procedures)
  notificationCreate,
  notificationGetMine,
  notificationMarkRead,
  notificationBulkMarkRead,
  notificationMarkAllRead,
  notificationArchive,
  notificationGetStats,
  notificationGetPreferences,
  notificationUpdatePreferences,
  notificationCreateTemplate,
  notificationGetTemplates,

  // Immigration (FLAT procedures)
  immigrationCreateCase,
  immigrationListCases,
  immigrationGetCaseById,
  immigrationUpdateCase,
  immigrationArchiveCase,
  immigrationGetDocumentRequirements,
  immigrationCreateDocumentRequirement,
  immigrationUpdateDocumentRequirement,
  immigrationGetCaseTimeline,
  immigrationCreateTimelineEvent,
  immigrationGetStats,
  immigrationGetUpcomingDeadlines,

  // GRA Integration (FLAT procedures)
  graAuthenticate,
  graSyncClient,
  graSubmitFiling,
  graCheckSubmissionStatus,
  graGetFilingCalendar,
  graExportClientData,

  // OCR (FLAT procedures)
  ocrProcessDocument,
  ocrGetProcessingStatus,
  ocrGetExtractedData,
  ocrValidateResults,
  ocrGetProcessingStats,
  ocrBatchProcess,
  ocrGetBatchStatus,

  // Property Management (FLAT procedures)
  propertyManagementPropertiesList,
  propertyManagementPropertiesGetById,
  propertyManagementPropertiesCreate,
  propertyManagementPropertiesUpdate,
  propertyManagementPropertiesDelete,
  propertyManagementPropertiesStats,
  propertyManagementTenantsList,
  propertyManagementTenantsGetById,
  propertyManagementTenantsCreate,
  propertyManagementTenantsUpdate,
  propertyManagementTenantsDelete,
  propertyManagementLeasesList,
  propertyManagementLeasesGetById,
  propertyManagementLeasesCreate,
  propertyManagementLeasesUpdate,
  propertyManagementLeasesTerminate,
  propertyManagementLeasesGetExpiring,
  propertyManagementPaymentsList,
  propertyManagementPaymentsRecordPayment,
  propertyManagementPaymentsUpdatePayment,
  propertyManagementPaymentsGetOverdue,
  propertyManagementMaintenanceList,
  propertyManagementMaintenanceCreate,
  propertyManagementMaintenanceUpdate,
  propertyManagementInspectionsList,
  propertyManagementInspectionsCreate,
  propertyManagementInspectionsComplete,

  // Training (FLAT procedures)
  trainingCoursesList,
  trainingCoursesGetById,
  trainingCoursesCreate,
  trainingCoursesUpdate,
  trainingCoursesPublish,
  trainingCoursesStats,
  trainingSessionsList,
  trainingSessionsGetById,
  trainingSessionsCreate,
  trainingSessionsUpdate,
  trainingSessionsOpenRegistration,
  trainingRegistrationsList,
  trainingRegistrationsCreate,
  trainingRegistrationsUpdateStatus,
  trainingRegistrationsMarkAttendance,
  trainingCertificatesList,
  trainingCertificatesIssue,
  trainingCertificatesVerify,
  trainingInstructorsList,
  trainingInstructorsCreate,
  trainingInstructorsUpdate,

  // Expediting (FLAT procedures)
  expeditingRequestsList,
  expeditingRequestsGetById,
  expeditingRequestsCreate,
  expeditingRequestsUpdate,
  expeditingRequestsAssign,
  expeditingRequestsComplete,
  expeditingRequestsStats,
  expeditingActivitiesList,
  expeditingActivitiesCreate,
  expeditingAgencyContactsList,
  expeditingAgencyContactsCreate,
  expeditingAgencyContactsUpdate,
  expeditingQueueList,
  expeditingQueueCreate,
  expeditingQueueUpdateStatus,

  // Local Content (FLAT procedures)
  localContentRegistrationsList,
  localContentRegistrationsGetById,
  localContentRegistrationsCreate,
  localContentRegistrationsUpdate,
  localContentRegistrationsApprove,
  localContentRegistrationsStats,
  localContentPlansList,
  localContentPlansCreate,
  localContentPlansUpdate,
  localContentPlansSubmit,
  localContentReportsList,
  localContentReportsCreate,
  localContentReportsUpdate,
  localContentReportsSubmit,
  localContentVendorsList,
  localContentVendorsCreate,
  localContentVendorsUpdate,
  localContentChecklistsList,
  localContentChecklistsCreate,
  localContentChecklistsUpdateItem,

  // Partner Network (FLAT procedures)
  partnerNetworkPartnersList,
  partnerNetworkPartnersGetById,
  partnerNetworkPartnersCreate,
  partnerNetworkPartnersUpdate,
  partnerNetworkPartnersDelete,
  partnerNetworkPartnersVerify,
  partnerNetworkPartnersUpdateTier,
  partnerNetworkPartnersStats,
  partnerNetworkReferralsList,
  partnerNetworkReferralsGetById,
  partnerNetworkReferralsCreate,
  partnerNetworkReferralsUpdate,
  partnerNetworkReferralsAccept,
  partnerNetworkReferralsComplete,
  partnerNetworkReferralsDelete,
  partnerNetworkAgreementsList,
  partnerNetworkAgreementsGetById,
  partnerNetworkAgreementsCreate,
  partnerNetworkAgreementsUpdate,
  partnerNetworkAgreementsDelete,
  partnerNetworkAgreementsActivate,
  partnerNetworkReviewsList,
  partnerNetworkReviewsGetById,
  partnerNetworkReviewsCreate,
  partnerNetworkReviewsModerate,
  partnerNetworkReviewsAddResponse,
  partnerNetworkReviewsDelete,
  partnerNetworkCommunicationsList,
  partnerNetworkCommunicationsGetById,
  partnerNetworkCommunicationsCreate,
  partnerNetworkCommunicationsMarkFollowUpComplete,
  partnerNetworkCommunicationsGetPendingFollowUps,
  partnerNetworkCommunicationsDelete,

  // Service Catalog (spread - flat internally)
  ...serviceCatalogRouter,
};

export type AppRouter = typeof appRouter;
export type AppRouterClient = RouterClient<typeof appRouter>;
